import FeatureCard from "../components/FeatureCard";
import meetEcoForecast from "../assets/Home/satellite.png";
import aboutStepwat from "../assets/Home/sagebrush.png";
import backedByScience from "../assets/Home/field-research.png";
import { ReactNode } from "react";
import { GoArrowUpRight } from "react-icons/go";
import { HiChevronRight } from "react-icons/hi2";

interface LinkWithUnderlineProps {
    href: string;
    external?: boolean;
    children: ReactNode;
}

const LinkWithUnderline = ({ href, external, children }: LinkWithUnderlineProps) => (
    <a
        href={href}
        {...(external ? { target: "_blank", rel: "noopener noreferrer" } : {})}
        className="flex items-center relative group"
    >
        {children}
        <span className="absolute left-0 bottom-[-2px] w-full h-[1px] bg-black opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
    </a>
);

const Info = () => {
    return (
        <div className="mx-auto px-5 sm:px-10 md:px-5 md:w-[1088px]">
            <FeatureCard
                title="Meet EcoForecast"
                description="This online app, featuring data generated by STEPWAT2 across 14 Western US states, allows land managers, farmers, foresters, and ranchers to visualize and simulate future dryland plant ecosystem dynamics based on plant functional types, climate scenarios, and land use factors."
                image={meetEcoForecast}
                imageAlt="Satellite view"
                imagePosition="left"
                className="my-24"
                links={<>
                    <LinkWithUnderline href="/app" external>Launch app <GoArrowUpRight size={15} className="ml-1" /></LinkWithUnderline>
                    <LinkWithUnderline href="/getting-started">Getting started <HiChevronRight size={14} className="ml-1" /></LinkWithUnderline>
                </>}
            />

            <FeatureCard
                title="About STEPWAT2"
                description="STEPWAT2 is a simulation model that assesses climate change and disturbance impacts on dryland plant communities. Using a process-based soil water model, it predicts how soil moisture and disturbances alter plant composition and biomass."
                image={aboutStepwat}
                imageAlt="Sagebrush ecosystem"
                imagePosition="right"
                className="my-24"
                links={<>
                    <LinkWithUnderline href="/stepwat2">Use STEPWAT2 <HiChevronRight size={14} className="ml-1" /></LinkWithUnderline>
                    <LinkWithUnderline href="/overview">Documentation <GoArrowUpRight size={15} className="ml-1" /></LinkWithUnderline>
                </>}
            />

            <FeatureCard
                title="Backed by science"
                description={<>STEPWAT2 was validated using field data from 15 big sagebrush sites. Simulated big sagebrush biomass correlated with field measurements and simulated densities match field data. Total shrub and herbaceous biomass simulations are within one standard deviation of field measurements, demonstrating the model&apos;s accuracy.</>}
                image={backedByScience}
                imageAlt="Dryland ecosystem field researchers"
                imagePosition="left"
                className="my-24"
                links={
                    <LinkWithUnderline href="https://doi.org/10.1002/ecs2.2394" external>
                        Read the paper <GoArrowUpRight size={15} className="ml-1" />
                    </LinkWithUnderline>
                }
            />
        </div>
    );
};

export default Info;
